---
# tasks file for ansible-role-iam
# for AIX servers 

- name: Useradd on Linux server
  shell: "/usr/bin/mkuser gecos={{ iam_gecos }} id={{ iam_uid }} pgrp={{ iam_primary_g }} groups={{ iam_supplementary_g }}"
  tags:
    - add_user

- name: Userdel on Linux server
  shell: "/usr/sbin/userdel -r {{ iam_uid }}"
  tags:
    - remove_user

- block:
  - name: Reset faillog
    shell: "chuser unsuccessful_login_count=0 {{ iam_uid }}"

  - name: Unlock user account
    shell: "chuser account_locked=false {{ iam_uid }}"

  - name: Reset password on Linux server
    shell: "echo '{{ iam_pwd }}' | passwd {{ iam_uid }} --stdin"
  tags:
    - reset_user
