---
# tasks file for ansible-role-iam
# for Linux servers 

- block:

  - name: Pre-check for the username
    become: true
    getent: 
      database: passwd
      key: "{{ iam_username }}"
      fail_key: true
    ignore_errors: true

  - name: User already exists
    fail:
      msg: "{{ iam_username }} already exists!"
    when: getent_passwd is defined

  - name: Useradd on Linux server
    become: true
    user:
      name: "{{ iam_username }}"
      comment: "{{ iam_gecos }}"
      uid: "{{ iam_uid | default(omit) }}"
      group: "{{ iam_primary_g | mandatory }}"
      groups: "{{ iam_supplementary_g | mandatory }}"
      state: present
    when: getent_passwd is undefined
    register: useradd
    ignore_errors: true

  - name: UID is not unique
    fail:
      msg: UID in not unique!
    when: useradd.rc == 4
 
  - name: UID is not unique
    fail:
      msg: User creation failed!
    when: useradd.rc != 0

  - name: Defined group doesn't exist!
    fail:
      msg: At least one of the groups defines does not exist!
    when: useradd.rc == 6

  tags:
    - iam-add-user

- name: Userdel on Linux server
  become: true
  user:
    name: "{{ iam_username }}"
    remove: yes
    state: absent
  tags:
    - remove_user

- block:
  become: true
  - name: Unlock user account
    shell: "passwd -u {{ iam_username }}"

  - name: Reset faillog
    shell: "faillog -r {{ iam_username }}"

  - name: Reset password on Linux server
    user:
      name: "{{ iam_username }}"
      password: "{{ iam_pwd | password_hash('sha512') }}"
      state: present

  - name: Password must be expired
    shell: "chage -d 0 {{ iam_username }}"
  tags:
    - reset_user
